mde/ejs

- README.md
- lib/ejs.js
- test/ejs.js
- test/fixtures/user-no-with.ejs
This option controls whether or not to use `with() {}` in the generated funcs. It is useful for performance purposes. EJS v1 had this option as well, albeit undocumented.
> Add `_with` option 

- package.json
- test/mocha.opts
Less cluttered package.json. This has the additional benefit of being able to directly run `mocha` without `npm test`.
> Move mocha opts to test/mocha.opts

- lib/ejs.js
Also do not override `context`, which is the newer option.
Fixes #19.
> Fix `scope` handling

- lib/ejs.js
With or without this patch, `compileDebug === true`:
```js
var __line = 1
, __lines = "<ul>\n  <% if (users) { %>\n    <p>Has users</p>\n  <% } %>\n</ul>"
, __filename = undefined;
try {
var __output = "";
with (locals || {}) {
;__output += "<ul>\n  ";;
__line = 2;;
if (users) {
;__output += "\n    <p>Has users</p>\n  ";;
__line = 4;;
}
;__output += "\n</ul>";;
__line = 5;
}
return __output.trim();
}
catch (e) {
rethrow(e, __lines, __filename, __line);
}
```
Without this patch, `compileDebug === false`:
```js
var __output = "";
with (locals || {}) {
;__output += "<ul>\n  ";;
__line = 2;;
if (users) {
;__output += "\n    <p>Has users</p>\n  ";;
__line = 4;;
}
;__output += "\n</ul>";;
__line = 5;
}
return __output.trim();
```
The `__line`s are completely useless.
With this patch, …
> Do not include __line in function unless compileDebug is true

- lib/ejs.js
The outer `()` already denotes a group.
Old:
http://tinyurl.com/oppjkyk
New:
http://tinyurl.com/ph7s979
> Simplify tag matching regex

- lib/ejs.js
- test/ejs.js
- test/fixtures/include-simple.html
- test/fixtures/include.css.html
- test/fixtures/include.html
- test/fixtures/include_preprocessor.css.html
- test/fixtures/include_preprocessor.html
Fixes #60.
Q: is this a breaking change? Should we maintain compat with 2.x behavior or 1.x behavior?
> Don't .trim() unconditionally

- .gitignore
- jsdoc.json
- lib/ejs.js
- lib/utils.js
- package.json
As much as I hate the boilerplates in JSDoc, it is still the *de facto* standard for inline JavaScript API documentation.
This is not designed for directly outputing to the website. I will add a more beginner-friendly api.md later.
> JSDoc annotations

- lib/ejs.js
- lib/utils.js
One hack for another, which one is better?
> Override escape's toString() instead of special casing it

- lib/ejs.js
Progress for #83.
Should I even bother with unit tests for this change? Is there even a reasonable way to achieve them? Either way, existing ones pass, and also our internal systems pass too, using modified code.
IIFE is 24 bytes, but when minfied, `__output` becomes 1 byte instead of 8, and it's repeated at least thrice - `var`, `return` and at least one `push`, so no harm done.
> IIFE inside `with` for better minification

- lib/ejs.js
Progress for #83 
This might have an effect on performance (I think I've seen something somewhere about `bind` being slow-ish) and also won't render on IE8 without a `bind` shim - I'm using this version and all tests pass in our system: https://github.com/facebook/react/blob/master/src/test/phantomjs-shims.js
> `__pushToOutput()` minifies better than `__output.push()`

- README.md
Fixes #152. I forgot to include the fix note in the commit message, so you'll have to close the issue manually.
Could @mde or @TimothyGu merge this?
> Add warning for ejs.render(dataAndOptions)

- docs/syntax.md
As noted in #137, api.md does not exist. Now references the appropriate section of the README.
**This does not resolve issue #137.**
> Remove reference to non-existent api.md

- README.md
No-conflict alternative to #159.
---
**Here is the original PR message:**
They were listed under Features, but not under Tags.
I also added a link to syntax.md from the README.
> Add whitespace slurping tags to README

- lib/ejs.js
The [PR 129](https://github.com/mde/ejs/pull/129) fixed issue 119, but would lost the include line's error information(such as his sample, we can't get error 'ejs/sample/index.html:18'). On the other way, his solution would make error filename wrong when you use both <%include('header.html')%> and <%-include body.html%>.
So I think this solution makes things better. After using this PR, as his sample, the error information displays as bellow.
```
ReferenceError: /Users/Spikef/ejs/sample/index.html:18
16| this_variable_is_not_defined is not defined
17| -->
>> 18| <% include body.html %>
19| </body>
20| </html>
/Users/Spikef/ejs/sample/body.html:2
1| 
>> 2| <p><%= this_variable_is_not_defined %></p>
```
> A better solution for PR 129

- README.md
I'm not sure if there was a specific reason to use `'` instead of ``` ` ``` there, but I guess it looks better like this. 😁
> Highlight inline code

- test/ejs.js
@TimothyGu I don't know if this is too hacky, but this is the only way I can think how to test it. If it looks good to you, please merge this.
My text editor trimmed some trailing whitespace as well.
**Before:**
```
=============================== Coverage summary ===============================
Statements   : 95.17% ( 276/290 ), 3 ignored
Branches     : 88.65% ( 164/185 ), 6 ignored
Functions    : 100% ( 32/32 )
Lines        : 95.17% ( 276/290 )
================================================================================
```
**After:**
```
=============================== Coverage summary ===============================
Statements   : 95.86% ( 278/290 ), 3 ignored
Branches     : 89.73% ( 166/185 ), 6 ignored
Functions    : 100% ( 32/32 )
Lines        : 95.86% ( 278/290 ) …
```
> Add tests for strict mode

- lib/ejs.js
Reverts part of 27b7b9c2c8770b6f05e43fff3b1b38bd69a4ca4e (#169)
This was a breaking change for some express users
Fixes #196 
~~**Do not merge yet, waiting for a reply to https://github.com/mde/ejs/issues/196#issuecomment-242086552.**~~
> Revert express auto 'root' option

- README.md
@IonicaBizau did a great job of building an online EJS playground, and I think it would be nice to link to it from the README.
Try it here: https://ionicabizau.github.io/ejs-playground/. The repo is: https://github.com/IonicaBizau/ejs-playground
CC: @mde @TimothyGu
> Add link to ejs-playground

- Jakefile
- package.json
Use git-directory-deploy.
This is my attempt at https://github.com/mde/ejs/issues/137.
@mde @TimothyGu Review?
> Auto-deploy JSDocs to gh-pages after jake publish

- .eslintignore
- lib/ejs.js
- test/ejs.js
The .eslintignore was misconfigured. In an attempt not to validate the browserified bundles, we added `ejs.js` to the .eslintignore. This not only ignored the bundle, it also ignored `lib/ejs.js` & `test/ejs.js`. This line was corrected to read `/ejs.js`.
As a result of this, quite a few linting errors needed fixed.
I will merge this in a few days if there are no corrections.
> Fix .eslintignore and lint errors

- package.json
- test/fixtures/no.newlines.error.ejs
This was causing tests to fail in mocha v3.1.0. Since this is fixed we are unpinning the mocha version.
Reverts e36b7595edd6a54f2b3f8b4fa5e8ee199c0564e9.
Fixes #206.
> Fix global variable leak in tests

- lib/ejs.js
- test/ejs.js
Since there is not a constructor and thus a constructor.name
for detection this provides a name that can be used for the same
purpose. This is useful for application servers that allow the
template engine to be passed in.
I am working on PRs for other template engines for this as well.
It should also be noted that Handlebars, lodash, and underscore
are all detectable through this method already.
doT: https://github.com/olado/doT/pull/216
Jade/Pug: https://github.com/pugjs/pug/pull/2630
> Adds a name attribute for easy identification

- README.md
- docs/jsdoc/fileLoader.jsdoc
- lib/ejs.js
- test/ejs.js
For security reasons, Sometimes the template file may have some
pre-processing.For example, inserts some checking data in the form of
time reading the html file.
This amendment provides similar 'cache' to set custom fileloader.
``` js
ejs.fileLoader = MyFileLoader;
```
resolve mde/ejs#125
> Feat: fileload should be independent

- lib/ejs.js
- lib/utils.js
These changes improve the performance of the `ejs.renderFile()` function by up to about 4x.
To be clear, the improvement is just in the `renderFile()` function, not the entire rendering process.
This increase in performance was achieved by:
+ Not calling `Array.prototype.slice` on the `arguments` object and then manipulating the returned array
+ Creating a global `_OPTS_EXPRESS` variable instead of manipulating the `_OPTS` array on every call to `renderFile()`
+ Moving the try-catch statement into its own function so that `renderFile` may be optimized by V8
+ Using a regular `for` loop in `utils.shallowCopyFromList()` instead of a `forEach` loop
```js
'use strict';
const Benchmark = require('benchmark');
const ejs = require('ejs');
const ejs2 = require('/path/to/this/branch/ejs');
const …
```
> Improve performance of the renderFile() function by up to 4x

- .gitignore
- .npmignore
- Jakefile
The test directory is currently 308K, everything else is 124K.
Not sure if this has already been considered (if so sorry), but not publishing the `test/` directory would make the module much smaller. If people want to run the tests, they can (and probably already are) pulling from GitHub instead.
> Add .npmignore file and don't publish test/

- lib/ejs.js
By moving the closure from scanLine (which is called frequently( to a normal function, the execution is speed up.
The changes to "line" made by _addOutput are not needed by scanLine. 
scanLine returns after calling _addOutput, except for one case when line is a closing token [-_]%> that has no spaces, or other content that would be changed in _addOutput.
So this change should be safe.
> avoid creating closure in frequent called scanLine

- lib/ejs.js
This improve performance for Includes.
Old code joins the _output array of each included file separately, and then joins all the results.
Old code also needs to create an _append closure for each included template.
The patch passes the _append of the master template to the includes, and saves time.
-----------
This has a positive side effect: if an include file define a function, and that function is somehow made accessible outside the function file, then calling it will add the functions _append in the place where it is called.
I don't think this will break anythink:
1) Currently such a function would be very hard to archive. It could be added to a local variable, and then used on the outside. 
2) If on did this, it would not get any results with current ejs, because the function would …
> use only one __output array for template and includes

- lib/utils.js
If the cache is used outside of ejs, a remove function becomes useful to invalidate a single object.
> add remove function to cache

- docs/jsdoc/options.jsdoc
- lib/ejs.js
[KumaScript](https://github.com/mdn/kumascript) and other modern EJS‑using projects doesn’t need this, so it just slows down template compilation time where the EJS compiler tries to find `include` directives.
> feat: Support disabling legacy `include` preprocessor directives

- test/ejs.js
I forgot to write tests in #458.
> test: Assert that disabling legacy includes works correctly

- lib/ejs.js
This commit adds a sourceURL directive to the generated template function.
This makes generated template code visible in the debugger.
See https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources
When loading templates dynamically in the browser (for example using [ejs-render-remote)](https://github.com/S2-/ejs-render-remote) this simple addition is really useful:
> Show compiled templates in debugger

- lib/ejs.js
- test/ejs.js
Currently, `ejs.compile('<%= await foo() %>')` won't say anything about needing to pass `async: true`.
> fix: Correct error message when `async != true`

- lib/ejs.js
- test/ejs.js
This sets the `name` property for the compiled function, so that it matches `opts.filename` without the file extension.
I also made it so that the default name would be `anonymous` instead of `returnedFn`, to match what the `Function` constructor sets the `name` to.
> feat: Set compiled function name

- README.md
- docs/syntax.md
This fixes the language used for syntax highlighting EJS code blocks in Markdown documentation files.
> docs: Fix EJS code block language

- benchmark/bench-ejs.js
- lib/ejs.js
Switching from pushing to an array and using `.join()` to using simple string concatenation yields performance gains up to 260%.
```
name:                          avg        med        med/avg    min        max                  loops
single tmpl compile:           0.671      0.66       0.663      0.651      0.728                20000
single tmpl compile (debug):   0.726      0.722      0.721      0.711      0.767                20000
large tmpl compile:            2.055      2.04       2.04       2.022      2.142                 1000
include-1 compile:             0.445      0.44       0.44       0.438      0.465                20000
-
single tmpl cached:            0.108      0.104      0.104      0.101      0.12                 50000
single tmpl cached (debug):    0.172      0.171 …
```
> Use string concatenation to build the output string

- README.md
The `beautify` option documentation was missing.
It took me hours until I could figure out why I wasn't able to use ES6 features with EJS, using this loader. Hopefully this should make it easier for others to use this loader to compile EJS templates with ES6 features.
Thanks for considering the patch and for this loader.
Best,
Rodrigo.
> Explain how to use ES6 features and documents the beautify option

- docs/syntax.md
There is a small typo in docs/syntax.md.
Should read `preceding` rather than `preceeding`.
> docs: Fix simple typo, preceeding -> preceding

- .gitignore
- README.md
- examples/hello.ejs
- examples/output-function.ejs
- examples/output-function.js
- lib/ejs.js
I've purposed implementing an `includer` function passed through options (https://github.com/mde/ejs/issues/500), but now I realized that EJS already supports array of `views` paths (not documented ?), it makes easy to add support for `root` array to handle includes with absolute path from multiple directories :relaxed: 
Although not as flexible as an `includer` function, this should be enough for my case and may require fewer changes to the lib, so I'm suggesting it first.
Anyway, I still available to try https://github.com/mde/ejs/issues/500 if it’s still a good idea, wdyt @mde ?
> Feat/ Support array of 'root' directories to include

- .github/workflows/create-release.yml
Automatically create GitHub release when new version tag is created, it's specially useful to notify GitHub users subscribed on repo to _Watch releases_.
> CI/ Create release

- bin/cli.js
Includes don't currently work with the cli (see https://github.com/mde/ejs/issues/521), this fixes the problem by specifying the current working directory as a default view.
> Fix cli includes

- bin/cli.js
- lib/utils.js
- test/cli.js
Passthrough hyphen case cli options (open-delimeter, close-delimeter, rm-whitespace, etc.) were getting parsed as `pOpts['camelCase']` but later fetched as `opts['hyphen-case'] = pOpts['hyphen-case']` (`opts` is later used in `ejs.render()`). This would lose any hyphen case options as `pOpts['rm-whitespace']` would be undefined but `pOpts['rmWhitespace']` would be what you really needed.
> Fix cli passthrough options

- lib/ejs.js
- test/ejs.js
I ran into #451 over the weekend. `outputFunctionName` is a somewhat fairly common way to get Remote Code Execution from a preexisting prototype pollution vulnerability in another library. (https://www.google.com/search?q=outputFunctionName+ctf has 1500+ hits). This hints to me that people might actually rely on this in the wild fairly often.
It is true that it would be preferrable for all libraries (or the language itself) to completely avoid/prevent Prototype Pollution so most people do not have to think of effects. At the same time the reality is that at any given time there are always a few live vulnerabilities. As a popular node it's a good idea for `ejs` to take a few extra actions to prevent widespread pollution->RCE escalation.
Hope this makes sense. I'm definitely flexible in …
> Mitigate prototype pollution effects

- lib/utils.js
- package.json
- test/utils.js
_Note: examples use the Node.js REPL with strict mode: `node --use_strict`._
Objects in JavaScript [inherit properties from their prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain). For example, the "toString" property can be accessed on all objects, but it doesn't actually exist on each object, it exists on the global Object prototype:
```js
let obj = {};
obj.toString();
// '[object Object]'
Object.getOwnPropertyDescriptor(obj, 'toString');
// undefined
Object.getOwnPropertyDescriptor(Object.prototype, 'toString');
// { value: [Function: toString], writable: true, enumerable: false, configurable: true }
```
Under normal circumstances, you can assign a property to an object using the `=` operator, and any property of the same name …
> Make escapeXML work when the Function prototype is frozen

- README.md
The async option description in the documentation was missing a closing parenthesis. This commit adds the closing parenthesis to correctly complete the sentence.
> fix: add missing closing parenthesis in async option description

- README.md
Following usejsdoc.org takes the user to a fake amazon page
> Replace usejsdoc.org with jsdoc.app
