- README.md
- package.json
This pull request is a combination of 4 commits:
- Do not claim node <0.10 support
- README: add devDependencies tracking badge
- Looser dependency version tracking
- Use Shields.io badges
See the commit message of each for additional information.
> Dependency improvements

- CHANGELOG.md
- lib/ejs.js
- test/ejs.js
- test/fixtures/include-abspath.ejs
> Fix absolute path inclusion

- CHANGELOG.md
- lib/ejs.js
- test/ejs.js
- test/fixtures/literal.ejs
- test/fixtures/literal.html
> Fix rendering '<%%' without an end tag

- examples/client.html
- examples/functions.ejs
- examples/functions.js
- examples/list.ejs
- examples/list.js
- test/ejs.js
Ported from EJS v1 with lots of added documentation.
> Add some examples

- lib/ejs.js
> Format compile function

- docs/syntax.md
Right now only an md document.
> Add syntax documentation

- README.md
- docs/jsdoc/options.jsdoc
- lib/ejs.js
- test/ejs.js
- test/fixtures/rmWhitespace.ejs
- test/fixtures/rmWhitespace.html
It is not a full-fledged HTML minifier, nor will it be. It is designed to be as "safe" as possible.
Fixes #51.
> Add rmWhitespace mode

- lib/ejs.js
- test/ejs.js
> Add dependency tracking support

- lib/utils.js
Improves performance a little bit, see http://jsperf.com/jade-better-escape/2 and https://github.com/jadejs/jade-runtime/commit/ed1ef32a2124cafee266066682e08daef98e7aec
> cache character encoding function

- lib/ejs.js
- test/ejs.js
- test/fixtures/space-and-tab-slurp.ejs
- test/fixtures/space-and-tab-slurp.html
> Added space and tab slurp with <%_ and _%>

- lib/ejs.js
- test/ejs.js
> Fix : remove newlines on windows with \r\n

- README.md
> Add documentation for renderFile() and filename

- docs/jsdoc/template-functions.jsdoc
Fixes #144 
Sorry for the messy diff, I re-ordered the callbacks in template-functions.jsdoc and git didn't "get it."
Any objections or suggestions @mde or @TimothyGu?
**If nothing is said within two days, I will merge this.**
> Add JSDocs for IncludeCallback

- lib/ejs.js
Fixes #156 
Open to peer review.
CC: @mde @TimothyGu
> Document escapeXML function

- README.md
- docs/jsdoc/options.jsdoc
- lib/ejs.js
- test/ejs.js
- test/fixtures/include-root.ejs
Effect of `include` absolute path.
And auto settings 'root' in Express.
> Add "root path" option

- CHANGELOG.md
> updated version on README.md

- Jakefile
Use browserify's --standalone option.
Fixes #190
@TimothyGu Please review and merge this.
> Add UMD support for the browser

- .eslintignore
- .eslintrc.json
- Jakefile
- examples/functions.js
- examples/list.js
- lib/utils.js
- package.json
**I would like someone else to review & merge this.**
- Fixed code in `lib/utils.js`, `examples/`, and the `Jakefile` to comply with the eslint rules.
- Removed unneeded `var fs = require('fs')` in `Jakefile`
- Added `.eslintignore` file
- Set `"avoidEscape": true` in `.eslintrc.json` to allow for using double quotes when the string contains single quotes. See https://github.com/mde/ejs/blob/eslint/lib/utils.js#L52
---
@mde @TimothyGu Should we consider making linting part of the travis build?
> Add lint script and fix lint errors

- lib/ejs.js
@mde @TimothyGu Any objections? If not, I'll merge in ~3 days.
> Add EJS-Lint notice to syntax error message

- .eslintrc.json
- docs/jsdoc/options.jsdoc
- docs/syntax.md
- lib/ejs.js
> Remove trailing whitespace, add eslint rule

- Jakefile
- lib/ejs.js
As per https://github.com/mde/ejs/issues/218.
> Add CNAME file to generated docs, link to ejs.co from JSDocs

- test/ejs.js
- test/fixtures/include-escaped.ejs
- test/fixtures/include-escaped.html
- test/fixtures/include-expression.ejs
- test/fixtures/include-expression.html
test for include used in escape or in expression
as requested in #285
> test for include in expression or escaped

- lib/ejs.js
- test/ejs.js
- test/fixtures/include-nonexistent.ejs
as requested in the issue #303 
I don't think this requires any tests, the change is pretty straightforward..
> showing the name of the include file that can't be found

- lib/ejs.js
- test/ejs.js
Added native Promise support to `renderFile`. Checks for the existence of the `Promise` ctor before trying to use it.
> Added Promise support with capabilities test to renderFile

- README.md
Adding VSCode EJS integration to the readme.
> Adding IDE Integrations

- README.md
- examples/express/README.md
- examples/express/app.js
- examples/express/package.json
- examples/express/views/index.ejs
I struggled a bit getting the client side compiled templates working. Here is a minimal example based on the caveats section of the main readme. You mention in #140 that you'd accept a PR. Hopefully others find it useful.
> Client side ejs compiled with express middleware example

- lib/ejs.js
This commit exposes the template class so that it can be extended.
Issue: #410
> Expose Template class

- docs/jsdoc/callbacks.jsdoc
- docs/jsdoc/template-functions.jsdoc
- lib/ejs.js
- lib/utils.js
This improves the type information present in JSDoc comments.
---
Pre‑requisite for #461
> docs(JSDoc): Improve type information

- README.md
This removes the duplication of **EJS** and **Embedded JavaScript templates** and also moves the badges into the heading, which looks better IMO.
> docs(README): Improve main heading

- postinstall.js
Fix console "Thank you" siteurl
> upd postinstall.js

- README.md
> fix(docs): missing doc for open and close delimiters

- jakefile.js
- test/cli.js
- test/ejs.js
This enables running ejs tests on windows too :)
> introduced windows compatibility on tests

- package-lock.json
- package.json
Fixed npm audit alert by updating jsdoc to 3.6.7
> Updated jsdoc to 3.6.7

- bin/cli.js
- test/cli.js
Fix for the problem described in https://github.com/mde/ejs/issues/521#issuecomment-717538871
> Make relative paths in include work for cli

- README.md
- docs/jsdoc/options.jsdoc
See https://github.com/mde/ejs/blob/5919964ec3c98041c1c51fb5f7f782e5b4626fa3/lib/ejs.js#L165-L169
> root can be arrays.
